site_name: CodeLab Docs
site_description: Documentation for the CodeLab paint.net plugin.
site_author: Jason Wendt
repo_name: codelab-docs
repo_url: https://github.com/toehead2001/codelab-docs/
edit_uri: tree/master/docs
copyright: CodeLab Docs v20200707
theme:
    name: material
    icon:
        logo: material/file-document
    favicon:
    font: false
    palette:
        scheme: preference
        primary: blue
        accent: blue
markdown_extensions:
    - smarty
    - admonition
    - codehilite:
        guess_lang: false
    - pymdownx.superfences
    - pymdownx.keys
    - toc:
        permalink: true
